version: '3.7'

services:
  web:
    build: .
    command: gunicorn app.agent:app -w 2 -k uvicorn.workers.UvicornWorker --timeout 30 -b 0.0.0.0:8000 --limit-request-line 0 --limit-request-field_size 0 --log-level debug
    volumes:
      - ./config:/opt/app/config
      - ./tests/:/opt/app/tests
      - ./app:/opt/app/app
    ports:
      - 8002:8000
