#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

CRAWLER_API_PROXYCRAWL_TOKEN = os.getenv('CRAWLER_API_PROXYCRAWL_TOKEN')
CRAWLER_API_DEVICE = os.getenv('CRAWLER_API_DEVICE')
CRAWLER_API_COUNTRY = os.getenv('CRAWLER_API_COUNTRY')
CRAWLER_API_PORT = os.getenv('CRAWLER_API_PORT')
CRAWLER_API_FACEBOOK_USE_PROXYCRAWL = os.getenv('CRAWLER_API_FACEBOOK_USE_PROXYCRAWL')
CRAWLER_API_TWITTER_USE_PROXYCRAWL = os.getenv('CRAWLER_API_TWITTER_USE_PROXYCRAWL')
CRAWLER_API_SURVEYCAKE_USE_PROXYCRAWL = os.getenv('CRAWLER_API_SURVEYCAKE_USE_PROXYCRAWL')
CRAWLER_API_INSTAGRAM_USE_PROXYCRAWL = os.getenv('CRAWLER_API_INSTAGRAM_USE_PROXYCRAWL')
CRAWLER_API_LOG_PATH = os.getenv('CRAWLER_API_LOG_PATH')
CRAWLER_API_YOUTUBE_API_KEY = os.getenv('CRAWLER_API_YOUTUBE_API_KEY')
